//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spider.Web.test.E_BaseData {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblFactoryID;
	protected global::System.Web.UI.WebControls.Label lblPipelineID;
	protected global::System.Web.UI.WebControls.Label lblPipeParentID;
	protected global::System.Web.UI.WebControls.Label lblSiteID;
		protected global::System.Web.UI.WebControls.TextBox txtSiteNo;
		protected global::System.Web.UI.WebControls.TextBox txtSpecificDescription;
		protected global::System.Web.UI.WebControls.TextBox txtSiteStyle;
		protected global::System.Web.UI.WebControls.TextBox txtRemarks;
		protected global::System.Web.UI.WebControls.TextBox txtCanvasX;
		protected global::System.Web.UI.WebControls.TextBox txtCanvasY;
		protected global::System.Web.UI.WebControls.TextBox txtLinkNote;
		protected global::System.Web.UI.WebControls.TextBox txtArrowNote;
		protected global::System.Web.UI.WebControls.TextBox txtAlarmNote;
		protected global::System.Web.UI.WebControls.TextBox txtCanvasNoteText;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
