//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spider.Web.test.E_BaseData {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblFactoryID;
	protected global::System.Web.UI.WebControls.Label lblPipelineID;
	protected global::System.Web.UI.WebControls.Label lblPipeParentID;
	protected global::System.Web.UI.WebControls.Label lblSiteID;
	protected global::System.Web.UI.WebControls.Label lblSiteNo;
	protected global::System.Web.UI.WebControls.Label lblSpecificDescription;
	protected global::System.Web.UI.WebControls.Label lblSiteStyle;
	protected global::System.Web.UI.WebControls.Label lblRemarks;
	protected global::System.Web.UI.WebControls.Label lblCanvasX;
	protected global::System.Web.UI.WebControls.Label lblCanvasY;
	protected global::System.Web.UI.WebControls.Label lblLinkNote;
	protected global::System.Web.UI.WebControls.Label lblArrowNote;
	protected global::System.Web.UI.WebControls.Label lblAlarmNote;
	protected global::System.Web.UI.WebControls.Label lblCanvasNoteText;


       
    }
}
